#!/usr/bin/env bash

page='carondoEmployee'
site='https://perlt.net/'

npm install &&
json -I -f package.json -e 'this.homepage="'$site$page'"' &&
npm run build &&
echo Removing old folder and creating new one
ssh root@165.227.144.152 "rm -rf /var/www/$page/; mkdir /var/www/$page" &&
echo DONE &&
echo Sending build folder content to server &&
scp -r ./build/* root@165.227.144.152:/var/www/$page
