#!/usr/bin/env bash

page='carondoEmployee'
site='https://perlt.net/'
ip=165.227.144.152

edit='false'
ins="true"

while getopts 'e i' flag; do
  case "${flag}" in
    e) edit='true' ;;
    i) ins="false" ;;
  esac
done

if [ $ins == "true" ] 
then
    echo installing dep 
    npm install
fi

json -I -f package.json -e "this.homepage=\"$site$page\"" &&
npm run build &&
echo Removing old folder and creating new one
ssh root@$ip "rm -rf /var/www/$page/; mkdir /var/www/$page" &&
echo DONE &&
echo Sending build folder content to server &&
scp -r ./build/* root@$ip:/var/www/$page 

if [ $edit == "true" ]
then
	echo Edit remote default file
	ssh -t root@$ip "nano /etc/nginx/sites-available/default"
	ssh root@$ip "service nginx restart"
fi
